### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by SteveErickson-J**
1. Standardize the naming convention for the locations field, 
2. Populate empty cells in the position field with appropriate names  
3. Remove 3 positions in which the job was removed from company website

### CODE REVIEW

**Comment by Zackhardtoname** [comment]
Wow. Thank you so much sir! That's really helpful!

**Comment by Zackhardtoname** [comment]
Actually is it possible that you convert the info from the Notes column in row 5 and row 12 to the Class Year Requirement column? Also, could you change the column name Class Year Requirement to Class Year? Thank you!

**Comment by MercureTony** [comment]
> Actually is it possible that you convert the info from the Notes column in row 5 and row 12 to the Class Year Requirement column? Also, could you change the column name Class Year Requirement to Class Year? Thank you!

Can you clarify what you mean by `convert` please?

**Comment by Zackhardtoname** [comment]
See #22.

**Pull request closed without merging**
