### PR TITLE
adds many more companies 

### PR DESCRIPTION
**Pull request by coopslarhette**
and their locations, some details need finishing. may continue to fill out details tmw

### CODE REVIEW

**Comment by Zackhardtoname** [comment]
Wow! Sir. You are truly amazing!! Would you be interested in further (coding-based) collaboration?

**Comment by appsicle** [comment]
Most of these companies are not actually out yet. I've already tested every link and every company added in this pr is not actually open.

**Comment by coopslarhette** [comment]
ah yes that is true, I pretty much just pulled them from my own spreadsheet where I had a column indicating whether or not they’re open or closed. could add that if it is wanted but maintenance of that is difficult.

**Comment by ironsoul0** [comment]
IMHO, this will ruin the whole repo. What is the purpose of adding companies that do not have open positions yet? In this case, https://github.com/christine-hu/summer-2019-internships is a more convenient resource.

Please revert, @Zackhardtoname

**Comment by Zackhardtoname** [comment]
I will revert it as soon as I get back tonight. I am really sorry for the trouble!
@ironsoul0 @coopslarhette @appsicle

**Comment by coopslarhette** [comment]
I disagree, it is useful to have a place to conglomerate all companies that have or will have internships in 2020. as you said yourself it makes it easy to check each company url to see their university/internship page to check whether or not they have released internship positions yet, among other things. if that is not a functionality of the repo then do revert it.

**Comment by coopslarhette** [comment]
I have more thoroughly looked over christine’s repo and now I can understand why you would want to revert, up to you zack

**Comment by appsicle** [comment]
The purpose of this repository is to track opened internships, not all internships that will eventually open. Every cs student in the world knows what the top companies are. I can list all the top unicorns, FAANG, trendy startups, and companies off the top of my head forward and backward. The problem is that we aren't aware of when the job posting actually opens and its semi-important to apply early on. By adding every company that does internship programs, that dilutes all the actual open internships. @coopslarhette You had very good intentions with your PR but I think you missed the purpose of this repository.

**Comment by Zackhardtoname** [comment]
@ironsoul0 @coopslarhette @appsicle
I really appreciate coopslarhette's effort in contributing generously to this repo.

I'd also say it's pretty important to apply (as soon as) the position opens. Recruiters often send out interview invitations in rounds and have a fixed number of spots in mind.

I would be more careful in the future when merging pull requests. Thank you guys for bringing this to my attention.

**Comment by Zackhardtoname** [comment]
Also, if potentially problematic pull requests are closed, I think it's better to open a new issue that refers to the pull request so that people can see the conversation more easily.

**Pull request merged**
