### PR TITLE
Convert States to State Abbreviations

### PR DESCRIPTION
**Pull request by iljones00**
Standardized location names to use abbreviations for states rather than their full names.

### CODE REVIEW

**Comment by Zackhardtoname** [comment]
Thank you so much! Great work!

I am sorry. Do you think it’s better to have the city names only if available to save space? So even if a city is not well-known it should be fine because we both want to minimize the word amount.

If you think it's too much trouble, just let me know :)

**Comment by Zackhardtoname** [comment]
I actually made an issue (#19) for that, which you can close if you want to update.

**Comment by iljones00** [comment]
I think that having the city names and state abbreviations both would be necessary, just in case several states have the same city name and for clarity's sake. But no worries! Thank you so much for doing this, I'll be sure to refer to this repo many over the coming months and I am sure many other people will too.

**Comment by Zackhardtoname** [comment]
Makes sense. 
I just read this.
https://help.openstreetmap.org/questions/17126/duplicate-city-names-in-us-search
Thank you for your great wisdom!

**Pull request merged**
